### ISSUE TITLE
Unexpected data in xref table

### ISSUE THREAD

**Issue by Nyratas** [myokyawhtun/PDFMerger#11]
Hi,

We developed a simple webapp (using Laravel 5.1 and [the composer wrapper of this repo](https://github.com/clegginabox/pdf-merger)). Everything was working fine on our local developement environment (vagrant with Laravel's Homestead). But once we deployed it online on a server (with PHP 5.6), PDFMerger always throws the following exception when merging PDFs :

`Exception in pdf_parser.php line 191: Unexpected data in xref table`

The PDFs we're merging are generated by dompdf, and, as I said, did not have problems locally with the same version of PHP.

I found some forum posts describing similar problems, but none seems to give a working solution. Any ideas ?

Thank you !

**Comment by myokyawhtun** [comment]
Can you refer to this comment. 

https://github.com/myokyawhtun/PDFMerger/issues/7#issuecomment-92954876

Sorry for sending to you late as I'm not longer active in improving this PDFMerger.

**Comment by Nyratas** [comment]
Thank you for your response.

The PDFs I want to merge are generated by dompdf. When I try to download them separetly, everything looks fine (and after checking them, they don't seem to be corrupt).

Maybe it's the PDF version of the generated files. I'll have a look.

**Comment by mdunbavan** [comment]
Hi @Nyratas did you ever resolve this issue? I've just come across this now

**Comment by Nyratas** [comment]
@mdunbavan I don't remember how this story ended... But I know for sure we didn't find a solution for this specific issue. I think there were some process-changes later on and we didn't have to merge PDFs anymore. So no, can't help, sorry !

**Comment by mdunbavan** [comment]
@Nyratas when you say merging what do you mean?

**Comment by Nyratas** [comment]
@mdunbavan We generated two PDF files (they had different formats and stuff) and wanted to merge them in order to make a single downloadable PDF (one file containing the two previously generated files in a specific order).

**Comment by mdunbavan** [comment]
Mine is just a simple 1 pdf but on my local dev version it all works well as soon as I put this on staging it throws the error above. I thought it was an issue with the pdf created but thats not it all I can say is that it could be the version of the package or the php?

**Comment by Nyratas** [comment]
@mdunbavan We had the exact same environment locally and on staging, but still didn't work on staging server. I really don't know where this issue's coming from since we had same versions locked into a composer.lock...

**Comment by myokyawhtun** [comment]
@Nyratas isn't because of server specs especially RAM or memory allocated for PHP processing? I've had the problem before. Merging so many PDFs in my local machine without problem and didn't work on company's staging server. Later turn out because of PHP memory issue since staging server just set 16 M or something like that. @mdunbavan
