### ISSUE TITLE
Fatal error: Class 'PDFMerger' not found in /www/wwwroot/mysite/myokyawhtun/sample.php on line 5

### ISSUE THREAD

**Issue by neocake** [myokyawhtun/PDFMerger#38]
hi guys,
my page always die in fatal error:

> Fatal error: Class 'PDFMerger' not found in /www/wwwroot/mysite/myokyawhtun/sample.php on line 5

 could anyone help me ? 
thanks!

**Comment by neocake** [comment]
> I suppose you are `including` 'PDFMerger.php' from your 'sample.php'-file.
> Therefore, the 'PDFMerger.php' must be in the same directory. Is that the case?
'PDFMerger.php' is in the same directory with sample.php, 
and ,
 i have tried "use(or include) PDFMerger(or PDFMerger.php);" in sample.php , but the scripts just die in that fatal error.  
i need some help, thank you guys

**Comment by aderaHenry** [comment]
Do this:

```
use PDFMerger\PDFMerger;
require_once 'PDFMerger.php';

```
on sample.php. Write that on the top of the file

**Comment by neocake** [comment]
> Do this:
> 
> ```
> use PDFMerger\PDFMerger;
> require_once 'PDFMerger.php';
> ```
> on sample.php. Write that on the top of the file

thank you! your advice works!
but new fatal error comes:
`Fatal error: Class 'PDFMerger\TCPDI' not found in /www/wwwroot/mysite/myokyawhtun/PDFMerger.php on line 87`

**Comment by aderaHenry** [comment]
You're welcome. For the subsequent Error, put a backslash before the class name TCPDI to make it a qualified name, like so: 

`$fpdi = new \TCPDI;`

Do that for any subsequent Class not found error.

**Comment by ficsorr** [comment]
> ```
> use PDFMerger\PDFMerger;
> require_once 'PDFMerger.php';
> 
> $pdf = new PDFMerger();
> ```
> 
> 
> Problem solved, thank you all guys.

Nice, works fine. Had a lot of trouble before finding this simple solution. Thank you!

**Comment by bramanto** [comment]
> Do this:
> 
> ```
> use PDFMerger\PDFMerger;
> require_once 'PDFMerger.php';
> ```
> 
> on sample.php. Write that on the top of the file

Thank you so much @aderaHenry . The code works perfectly.

**Comment by fi5ly** [comment]
@aderaHenry thank you very much

**Comment by googlebe** [comment]
`use PDFMerger\PDFMerger;
require_once 'PDFMerger.php';

$pdf = new PDFMerger();`

oh,i am sorry,how can i do?i used the code,but the error still appear `Fatal error: Class 'PDFMerger\TCPDI' not found in D:\wnmp\nginx\www\pdfmerge\PDFMerger.php `

**Comment by Lichtschalter-5000** [comment]
> You're welcome. For the subsequent Error, put a backslash before the class name TCPDI to make it a qualified name, like so:
> 
> `$fpdi = new \TCPDI;`
> 
> Do that for any subsequent Class not found error.
As @aderaHenry wrote.

**Comment by manduzu** [comment]
Fatal error: Uncaught Error: Class 'PDFMerger' not found in C:\xampp\htdocs\pdf\index.php:17 Stack trace: #0 {main} thrown in C:\xampp\htdocs\pdf\index.php on line 17


hey guys what cause this error ill be happy is you will help with this error

**Comment by myokyawhtun** [comment]
@manduzu can you try like what neocake wrote before? 

```php
use PDFMerger\PDFMerger;
require_once 'PDFMerger.php';

$pdf = new PDFMerger();
```
