### ISSUE TITLE
Could not locate PDF on 'url'

### ISSUE THREAD

**Issue by Barralait** [myokyawhtun/PDFMerger#4]
Each time I try, I get this error. But when I do access the URL, the PDF is shown normally. Any ideas?

**Comment by MarvinVk** [comment]
I have the same problem it looks like it doesn't pass the "file_exists". So it already breaks at the "addPDF" function.

Could not locate PDF on 'http://hellocave.s3.amazonaws.com/employee-contracts/2017-03-08-070330_58bfb38ed4c74.pdf'

**Comment by myokyawhtun** [comment]
@MarvinVk let me check. 

With day to day operation in 9 to 5 work, I really don't have enough time to check on this project anymore. Few years back, I simply just forked from original developers and this repo become widely used for merging PDF files..
