### ISSUE TITLE
Class 'PDFMerger' not found

### ISSUE THREAD

**Issue by mahatej6** [myokyawhtun/PDFMerger#45]
Throwing error as :
Fatal error: Uncaught Error: Class 'PDFMerger' not found in XXXX\PDFMerger-master\sample.php:4 Stack trace: #0 {main} thrown in XXXX\PDFMerger-master\sample.php on line 4

**Comment by DEQ-Dave** [comment]
Make sure you have fPDF and FPDI loaded before you try to create an instance of \Clegginabox\PDFMerger\PDFMerger

**Comment by agamemnus** [comment]
What? How? This isn't Clegginabox.

**Comment by swetaranjan7** [comment]
Any solution on this?

**Comment by simranhmirza786** [comment]
use PDFMerger\PDFMerger;
require_once 'PDFMerger.php';

$pdf = new PDFMerger();

**Comment by simranmirzace** [comment]
You can use below Code:
use PDFMerger\PDFMerger;
require_once 'PDFMerger.php';

$pdf = new PDFMerger();

**Comment by myokyawhtun** [comment]
> Throwing error as :
> Fatal error: Uncaught Error: Class 'PDFMerger' not found in XXXX\PDFMerger-master\sample.php:4 Stack trace: #0 {main} thrown in XXXX\PDFMerger-master\sample.php on line 4

@mahatej6  make sure you import the PDFMerger library before you do it so.

```php
use PDFMerger\PDFMerger;
require_once 'PDFMerger.php';

$pdf = new PDFMerger();
```

**Comment by aldiazhar** [comment]
> Make sure you have fPDF and FPDI loaded before you try to create an instance of \Clegginabox\PDFMerger\PDFMerger

Hi @W1DJM , Would you explain that in more detail or suggest some documents I should read?

**Comment by guimafx** [comment]
Guys, 

You can MERGE PDF FILES in PHP using unix CAT cmd.

Like that

            $String = "pdftk file1.pdf file2.pdf cat output destination.pdf";
            shell_exec($String);

Att, 

Guilherme
