### ISSUE TITLE
Loosing hyperlink when merge pdf

### ISSUE THREAD

**Issue by luffyfr** [myokyawhtun/PDFMerger#51]
Hi,
I'm formatting pdf page with _wkhtmltopdf_, and after, i'm merging them.
hyperlink are right formatted with https:// ... and are working in each pages formatted with _wkhtmltopdf_.
But when pages merged with the library, i'm loosing hyperlink.
Is there an option to keep them ?

**Comment by laubelette** [comment]
Hi,
Same problem.
Did you find a solution ?
Thanks for your response

**Comment by pranavaeer** [comment]
Hi,
I'm also facing the same issue on merging i.e link tag doesn't work, if anyone found any solution for this, please respond.

**Comment by oleteacher** [comment]
In same boat, pdf's lose all links. Hoping for solution?

**Comment by weshouldfight** [comment]
Same problem! Any solution?

**Comment by luffyfr** [comment]
The only solution i found is to used another lib, i used setasign/fpdi and everything is ok now, in add with fpdi, you can add some protection to your pdf generated.

**Comment by vitorgabrieldev-archiver** [comment]
A mesma coisa

**Comment by guimafx** [comment]
Maybe could be solved.

   1. *Open a new terminal window*
   2. *Use cd to enter the directory with the PDF files you want to merge*
   3. *Run: pdfunite file1.pdf file2.pdf output.pdf*
   4. *Hit enter to let the tool merge the PDF files*
