### ISSUE TITLE
Warning in tcpdi_parser.php

### ISSUE THREAD

**Issue by federicogon** [myokyawhtun/PDFMerger#55]
While I was merging some files I get this error:
`Warning: count(): Parameter must be an array or an object that implements Countable in ./vendor/myokyawhtun/pdfmerger/tcpdf/tcpdi_parser.php on line 503`

**Solution**: replace line 503 on tcpdf/tcpdi_parser.php:
`} elseif (($key == '/Index') AND ($v[0] == PDF_TYPE_ARRAY AND count($v[1] >= 2))) {`
with 
`} elseif (($key == '/Index') AND ($v[0] == PDF_TYPE_ARRAY AND count($v[1]) >= 2)) {`

thanks

**Comment by chinlung** [comment]
It is indeed a problem with tcpdi_parser, after modifying it, there is no longer this error

**Comment by myokyawhtun** [comment]
@federicogon and @chinlung ... thank you
