### ISSUE TITLE
FPDF error: Unable to find pointer to xref table

### ISSUE THREAD

**Issue by itsazzad** [myokyawhtun/PDFMerger#7]
I am getting error: FPDF error: Unable to find pointer to xref table

**Comment by dazzz1er** [comment]
Hi @itsazzad from my experience this is caused by a corrupt PDF file. I've also had issues with PDF files of version higher than (I think 1.4), due to FPDF. Probably unhelpful to you after all this time!

**Comment by jamesexperts** [comment]
Yes
error: FPDF error: Unable to find pointer to xref table
Due to corrupt PDF file

**Comment by premmohantyagi** [comment]
Yes
error: FPDF error: Unable to find pointer to xref table
Due to corrupt PDF file
