### ISSUE TITLE
Callables of the form ["TCPDI", "TCPDF::SetFont"] are deprecated

### ISSUE THREAD

**Issue by a4992214** [myokyawhtun/PDFMerger#73]
I am experiencing the error:

`Deprecated:  Callables of the form ["TCPDI", "TCPDF::SetFont"] are deprecated in ..../PDFMerger/tcpdf/fpdf_tpl.php on line 278`.... when calling `$pdf->merge($a, $b)`

When using php8.2

Post edit: Looks like this is a duplicate of #68

**Comment by a4992214** [comment]
Looks like this is a duplicate of https://github.com/myokyawhtun/PDFMerger/issues/68

**Comment by Kps-96** [comment]
Patch:  fix-tcpdi-php83-deprecation.patch


--- a/vendor/iio/libmergepdf/tcpdi/fpdf_tpl.php
+++ b/vendor/iio/libmergepdf/tcpdi/fpdf_tpl.php
@@ -145,7 +145,7 @@ class FPDF_TPL extends FPDF {
     function endTemplate() {
         if (is_subclass_of($this, 'TCPDF')) {
             $args = func_get_args();
-            return call_user_func_array(array($this, 'TCPDF::endTemplate'), $args);
+            return TCPDF::endTemplate(...$args);
         }
         
         if ($this->_intpl) {
@@ -275,7 +275,7 @@ class FPDF_TPL extends FPDF {
     public function SetFont($family, $style = '', $size = 0, $fontfile='', $subset='default', $out=true) {
         if (is_subclass_of($this, 'TCPDF')) {
             $args = func_get_args();
-            return call_user_func_array(array($this, 'TCPDF::SetFont'), $args);
+            return TCPDF::SetFont(...$args);
         }
         
         parent::SetFont($family, $style, $size);
@@ -299,7 +299,7 @@ class FPDF_TPL extends FPDF {
     ) {
         if (is_subclass_of($this, 'TCPDF')) {
             $args = func_get_args();
-            return call_user_func_array(array($this, 'TCPDF::Image'), $args);
+            return TCPDF::Image(...$args);
         }
         
         $ret = parent::Image($file, $x, $y, $w, $h, $type, $link);
@@ -320,7 +320,7 @@ class FPDF_TPL extends FPDF {
     function AddPage($orientation = '', $format = '', $keepmargins = false, $tocpage = false) {
         if (is_subclass_of($this, 'TCPDF')) {
             $args = func_get_args();
-            return call_user_func_array(array($this, 'TCPDF::AddPage'), $args);
+            return TCPDF::AddPage(...$args);
         }
         
         if ($this->_intpl)
@@ -335,7 +335,7 @@ class FPDF_TPL extends FPDF {
     function Link($x, $y, $w, $h, $link, $spaces = 0) {
         if (is_subclass_of($this, 'TCPDF')) {
             $args = func_get_args();
-            return call_user_func_array(array($this, 'TCPDF::Link'), $args);
+            return TCPDF::Link(...$args);
         }
         
         if ($this->_intpl)
@@ -347,7 +347,7 @@ class FPDF_TPL extends FPDF {
     function AddLink() {
         if (is_subclass_of($this, 'TCPDF')) {
             $args = func_get_args();
-            return call_user_func_array(array($this, 'TCPDF::AddLink'), $args);
+            return TCPDF::AddLink(...$args);
         }
         
         if ($this->_intpl)
@@ -358,7 +358,7 @@ class FPDF_TPL extends FPDF {
     function SetLink($link, $y = 0, $page = -1) {
         if (is_subclass_of($this, 'TCPDF')) {
             $args = func_get_args();
-            return call_user_func_array(array($this, 'TCPDF::SetLink'), $args);
+            return TCPDF::SetLink(...$args);
         }
         
         if ($this->_intpl)
